// Mocks generated by Mockito 5.3.0 from annotations
// in pokedexapp/test/data/repositories/pokemon_repository_impl_test.dart.
// Do not manually edit this file.

// @dart=2.9

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedexapp/core/network/network_info.dart' as _i2;
import 'package:pokedexapp/data/datasources/pokemon_remote_datasource.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i2.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [RemotePokemonDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemotePokemonDataSource extends _i1.Mock
    implements _i3.RemotePokemonDataSource {
  MockRemotePokemonDataSource() {
    _i1.throwOnMissingStub(this);
  }
}
